### ISSUE TITLE
The implemented DSN in this repo seems different from the one mentioned in the essay

### ISSUE THREAD

**Issue by HZIH** [jamesYu365/EGAT#3]
Can you give me some explanation for better understanding of the DSN function defined in this repo?

**Comment by jamesYu365** [comment]
Thank you for your question. The DSN implementation was one of the main challenges I encountered while implementing EGAT. You can refer to `testlib.py`, where I explored several approaches to implement DSN. The final implementation is the most efficient solution I could find.
